pname: base
pop_size: 100
c_rate: 1.000000
f_factor: 0.500000
max_iters: 5000
coil_only: 0
allatom: 0
stage0_init: 0
stage2_interval: -1
stage2_all_interval: -1
partial_reset: -1
log_interval: 10
island_interval: 100
do_lsh: 0
n_hashes: 10
update_interval: 20
change_interval: 100
reset_d_trigger: 0.000000
reset_d_percent: 0.750000
reset_rmsd_percent: 0.000000
reset_rmsd_trigger: 0.000000
sade_run: 1
sade_lp: 50
sade_reinit_interval: 1000
do_crowding: 0
do_rmsd_crowding: 1
crowding_factor: 60
